[theme]
# base="dark"
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
# To match jbreffle.github.io text color use #93a1a1
font="sans serif"

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
# level = "debug"
